name: iwps
description: "Smart Water Purification System - IWPS App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  fl_chart: ^1.1.1      # For sensor data charts
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.2.2  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# ======================================================
#  App Icon Configuration
# ======================================================
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/icon.png